### ISSUE TITLE
Want to make the RMP link in place, just convert the Professor Name text to a link

### ISSUE THREAD

**Issue by shamystic** [williamyeny/duke-registration-enhancer#23]
This is probably super easy but I suck at JQuery

**Comment by shamystic** [comment]
Currently an additional text link is just added the box.

**Comment by williamyeny** [comment]
Hey Shamikh nice work!

I do want to bring up this, however: why would we want the professor's name to be a link? I think it might be better to have it as a separate element from a UX perspective:

1. Copying the professor's name (for whatever reason) might be harder as the user might accidentally click on the link
2. It is confusing when it is first encountered. For example, if the entire professor's name is a link, you may not know where the link redirects you to. However, if you have a separate button that says "RMP" or "rating", you have a pretty good idea of what it does, even if you have not seen it before
3. It will not be consistent with the rest of the elements. For example, none of the elements are links except the course number, and even then it opens a native modal with official Duke information. It may be a bit inconsistent to have a very key piece of information, the professor's name, to redirect to a new tab on a third party site.

These are all suggestions -- feel free to make your own decision.
